# Generated by Django 3.1.5 on 2021-01-31 08:17

import app_usweb.models.customusermanager
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('employee_cd', models.IntegerField(primary_key=True, serialize=False, verbose_name='社員番号')),
                ('email', models.EmailField(max_length=254, verbose_name='メール')),
                ('first_name', models.CharField(max_length=30, verbose_name='名')),
                ('last_name', models.CharField(max_length=30, verbose_name='姓')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効フラグ')),
                ('date_insert', models.DateTimeField(default=django.utils.timezone.now, verbose_name='登録日')),
                ('date_update', models.DateTimeField(default=django.utils.timezone.now, verbose_name='更新日')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
            managers=[
                ('objects', app_usweb.models.customusermanager.CustomUserManager()),
            ],
        ),
        migrations.CreateModel(
            name='code',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_name', models.CharField(max_length=20)),
                ('code', models.CharField(max_length=3)),
                ('code_de', models.CharField(max_length=30, null=True)),
                ('sort', models.DecimalField(decimal_places=0, max_digits=2, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='employee',
            fields=[
                ('employee_cd', models.DecimalField(decimal_places=0, max_digits=6, primary_key=True, serialize=False)),
                ('employee_name', models.CharField(max_length=15)),
                ('employee_name_kana', models.CharField(max_length=30, null=True)),
                ('hire_data_ym', models.DecimalField(decimal_places=0, max_digits=6)),
                ('hobby', models.CharField(max_length=10, null=True)),
                ('qualification1', models.CharField(max_length=3, null=True)),
                ('qualification2', models.CharField(max_length=3, null=True)),
                ('qualification3', models.CharField(max_length=3, null=True)),
                ('regist_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('department_cd', models.DecimalField(decimal_places=0, max_digits=3, null=True)),
                ('position_cd', models.DecimalField(decimal_places=0, max_digits=2, null=True)),
            ],
        ),
        migrations.AddConstraint(
            model_name='code',
            constraint=models.UniqueConstraint(fields=('code_name', 'code'), name='unique_booking'),
        ),
        migrations.AddField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
    ]
