# Generated by Django 3.1.5 on 2021-01-24 02:58

import app_usweb.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('employee_cd', models.IntegerField(primary_key=True, serialize=False, verbose_name='社員番号')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='メール')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='名')),
                ('last_name', models.CharField(blank=True, max_length=30, verbose_name='姓')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効フラグ')),
                ('date_insert', models.DateTimeField(default=django.utils.timezone.now, verbose_name='登録日')),
                ('date_update', models.DateTimeField(default=django.utils.timezone.now, verbose_name='更新日')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
            managers=[
                ('objects', app_usweb.models.CustomUserManager()),
            ],
        ),
    ]
