# Generated by Django 3.1.5 on 2021-01-27 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_usweb', '0002_auto_20210124_2136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=30, verbose_name='名'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=30, verbose_name='姓'),
        ),
    ]
